version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./api/uploads:/app/uploads
      - ./api/dist:/app/dist
    environment:
      - REDIS_URL=redis:6379
      - TEXLIVE_SERVICE_URL=http://compiler:8081
      - MAX_QUEUE_SIZE=10
      - MAX_FILE_SIZE=10485760 # 10MB
      - PDF_RETENTION_MINUTES=3
      - STATUS_RETENTION_MINUTES=10
    depends_on:
      - redis
      - compiler
    mem_limit: 256m
    restart: unless-stopped

  compiler:
    build: ./compiler
    ports:
      - "8081:8081"
    mem_limit: 512m
    restart: unless-stopped

  redis:
    image: "redis:7-alpine"
    mem_limit: 64m
    restart: unless-stopped
